server:
  port: 80

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  zipkin:
    base-url: http://192.168.21.130:9411/
    sender:
      type: web