server:
  port: 80

spring:
  autoconfigure:    #忽略数据库配置
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  cloud:
    gateway:
      globalcors:   #全局跨域
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:     #网关配置联调
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/admin/product/** # 路径匹配

  zipkin:   #链路追踪
    base-url: http://192.168.21.130:9411/
    sender:
      type: web