server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://192.168.21.130:3306/gmall_product?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  zipkin:
    base-url: 192.168.21.130:9411/
    sender:
      type: web